### ISSUE TITLE
Make it possible to specify network protocol type (tcp/udp/both) when port fowarding

### ISSUE THREAD

**Issue by nicjo814** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#10]

**Comment by subzero79** [comment]
Isn't that done automatically based on Dockerfile export port?

**Comment by nicjo814** [comment]
Well, maybe (if not I'll fix that). However I want to make custom port mappings with selectable protocol type.

**Comment by ikogan** [comment]
Only if you specify the `-P`, if you want to expose some ports and not others, you need to be able to specify protocol. FreeIPA, for example, wants to expose their ntp server on UDP 123 but since OMV has it's own NTP server and they share a clock, there isn't really a good reason to do that.
