### ISSUE TITLE
Add a button to see logs from containers

### ISSUE THREAD

**Issue by slobberbone** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#18]
Is it possible to add a button to display in a popup the result of docker logs mycontainer ?

**Comment by nicjo814** [comment]
Do you know which command would generate the log information?

**Comment by slobberbone** [comment]
docker logs mycontainer ;)

**Comment by nicjo814** [comment]
Perfect, just wanted to make sure I implement the correct thing :-) I'll add it in the next release.

**Comment by slobberbone** [comment]
Thanks !

**Comment by nicjo814** [comment]
Closed by 3518928a8f693b7d72cbf453f79eb952a7f1dfa4
