### ISSUE TITLE
Copy settings command (select image)

### ISSUE THREAD

**Issue by subzero79** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#23]
When we run a pull upgrade to update the contents of an template image, if there is running container his base image becomes now untagged.

Could it be possible that when we do copy (with the container stopped of course) are we able to pick from a dropdown the new image?
I don't know how we can relate the untagged from the new one, so i guess the dropdown will have to display all images.

This happens to me now since i try now to build my own images based on alpine to save space.

**Comment by nicjo814** [comment]
I just stumbled across this issue myself.

**Comment by subzero79** [comment]
Just to add in 3.0 when you press copy/modify container all the paths in the run dialog are displayed with the RO switch on.

**Comment by nicjo814** [comment]
RO is intentional. The idea is that all RO entries are "set" and may be modified by clicking the "edit" button. I know it's not the best implementation but I'm afraid it will have to do for now :-)

**Comment by subzero79** [comment]
Ok understand, thanks for the clarification.

**Comment by nicjo814** [comment]
Could you test with the new commits I've made? I've made it use the same image name as was used by the original container. I hope this is a good solution.

**Comment by subzero79** [comment]
Is fixed, this was also affecting the run image button. Guess we can close

**Comment by nicjo814** [comment]
Closed by 49d1a62cbff0738ace824663734c2b7bf6c7e7a1
