### ISSUE TITLE
Docker modify 3.0 does not retain port forward

### ISSUE THREAD

**Issue by subzero79** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#25]
In the the latest build from source, modify button works as expected on some parameters but fails on port forward.

When we click the modify button all port fordward are not displayed as in the currently running container. The problem comes even after manually adding the port forward to the modify dialog, the port is still not forwarded.

**Comment by nicjo814** [comment]
I'm trying to reproduce this but I fail... Could you provide exact steps performed and image used?

**Comment by subzero79** [comment]
I think the latest commits fix it in way that now shows the port forward ready as a configuration (like the plus button already pressed for the port), but when you press run the port is not forwarded.

I use this personal image

https://gist.githubusercontent.com/subzero79/aa878afd2eee601acb63/raw/b0ab45feb4e0260565715a8814a145f255a920c8/squid

**Comment by subzero79** [comment]
Can't seem to reproduce the issue right now, i was gonna make a screen video.
Let you know through the day so we can possibly close this

**Comment by nicjo814** [comment]
Can I close this issue?

**Comment by subzero79** [comment]
I though it was single proble, today i experienced this again with another image/container

Look at this screen video

https://dl.dropboxusercontent.com/u/54639/docker.mp4

**Comment by nicjo814** [comment]
Hmmm... Looking at your video I notice that when you open the modify dialogue the first time it says networking mode "Default" and I can't see any IP (0.0.0.0) in the configuration for port 8112. Both things are a bit suspicious :-) I'll try to dig into this some more. Do you know how you configured the container initially?

**Comment by subzero79** [comment]
Aha, understand i started the container in CLI, like

docker run -d --volumes-from=deluge-data -p 8112:8112 --name=deluge xataz/deluge:1.3-stable 

So you pass the explicit option --net=bridge always, that must be the issue. As i selected bridge and it works properly. So is my bad usage

Guess we can close now. 

Note: watch the video at the end the modify calls the exposed volumes to modify only in the host path, in this case i am calling the volumes from another container, so i am not ount binding.

**Comment by nicjo814** [comment]
Good catches both of them! I need to handle containers started from cli as long as the parameters provided are supported by the plugin (both network mode and volumes-from in this case). I'll fire up the same image here and take a look at the json data from "docker inspect" to see if I can correct this. I'll leave this issue open and close it when both problems are fixed.

**Comment by nicjo814** [comment]
I'll clode this issue and publish version 3.0.7 on Bintray.
