### ISSUE TITLE
[OMV 3.x] +[backport kernel]

### ISSUE THREAD

**Issue by happyreacer** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#31]
The openmediavault-docker-gui does not work with the backport kernel from the omv-extras.
many logs are on the omv-forum on the side:
[http://forum.openmediavault.org/index.php/Thread/11290-Docker-GUI-plugin-now-stable/?pageNo=22](url)
or exactly
http://forum.openmediavault.org/index.php/Thread/11290-Docker-GUI-plugin-now-stable/?postID=123269#post123269

can everybody fix it?

**Comment by luxflow** [comment]
http://log.rowanto.com/broken-docker-in-debian-jessie/ 
did you try this?
I'm currently running backport kernel + OMV 3 without problem

**Comment by subzero79** [comment]
There's no issue. The answer was given in the forum, there is no aufs driver in bpo kernel, you can switch to devicemapper or a dedicated btrfs disk for docker.

**Comment by happyreacer** [comment]
@luxflow yes it works, but i think it is  better to use for newbies when this is changed.
