### ISSUE TITLE
 Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by reey** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#32]
I'm receiving this error message:
Fehler
Object of class stdClass could not be converted to string
Fehler #0:
exception 'ErrorException' with message 'Object of class stdClass could not be converted to string' in /usr/share/openmediavault/engined/rpc/docker.inc:1461
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/docker.inc(1461): errorHandler(4096, 'Object of class...', '/usr/share/open...', 1461, Array)
#1 [internal function]: OMVRpcServiceDocker->getDockerRepo(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(84): OMV\Rpc\ServiceAbstract->callMethod('getDockerRepo', Array, Array)
#4 /usr/sbin/omv-engined(516): OMV\Rpc\Rpc::call('Docker', 'getDockerRepo', Array, Array, 1)
#5 {main}

I think it came with an update of OMV..
I'm using the newest version of OMV Erasmus..

**Comment by luxflow** [comment]
can you give me a more detail what do you do when you encounter error
and what packages do you install (dpkg -l | grep openm)

**Comment by reey** [comment]
I'm receiving this error, when I'm opening the Docker part of the Web GUI..
root@NAS:~# dpkg -l | grep openm
ii  openmediavault                       3.0.53                             all          Open network attached storage solution
ii  openmediavault-docker-gui            3.1.2                              amd64        OpenMediaVault plugin for Docker
ii  openmediavault-flashmemory           3.4.3                              all          folder2ram plugin for OpenMediaVault
ii  openmediavault-keyring               1.0                                all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-letsencrypt           3.1                                all          Generate free and valid SSL certificates for OMV
ii  openmediavault-minidlna              3.3.3                              all          OpenMediaVault miniDLNA (DLNA server) plugin
rc  openmediavault-mysql                 3.0.3                              all          MySQL plugin for OpenMediaVault.
ii  openmediavault-omvextrasorg          3.4.8                              all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-sensors               3.0                                all          Provides a cpu temperature monitor
ii  openmediavault-wol                   3.1                                all          OpenMediaVault WOL plugin

**Comment by luxflow** [comment]
I found what's wrong, this is due to missing github page 
But I don't have permission to edit github pages. so I will let repo admin to do action
So just wait, it will be fixed soon

@ryecoaaron  do you know why http://openmediavault-plugin-developers.github.io/ this github page disappear?

**Comment by ryecoaaron** [comment]
@luxflow, no I didn't even know it existed.  I'm guessing @nicjo814 created it?

**Comment by nicjo814** [comment]
I created it to store docker image configurations for the repo. It's obviously gone now though...

**Comment by ryecoaaron** [comment]
What was on it?  Can you recreate it?  Did someone delete it?

**Comment by nicjo814** [comment]
It was an xml file describing some Docker images, which was used to get info into the GUI. It was also logos for the various images. I'll have a look and see if it's available locally here. No idea who might have deleted it.

**Comment by nicjo814** [comment]
The repo is actually here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-repo (and looks healthy) but I used that other link to get direct access to the files. Maybe GitHub changed something in regards to how to access files.

**Comment by luxflow** [comment]
I cannot access http://openmediavault-plugin-developers.github.io/openmediavault-docker-repo/ now, Is github pages up right?

**Comment by ryecoaaron** [comment]
Couldn't you access that file with this link?  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-repo/gh-pages/dockerlist.xml

**Comment by luxflow** [comment]
the problem was not github pages but was linuxserver.io json [page](http://tools.linuxserver.io/docker-templates.json) , sorry, so @nicjo814  please edit that json to make `DuckDNS` have `Category` , also to prevent same situation I pushed commit for bad dockerRepo response (it is just try catch) so @ryecoaaron could you upload 3.1.3 deb?

**Comment by ryecoaaron** [comment]
Done.

**Comment by reey** [comment]
That seems to solve it, thanks!

**Comment by nicjo814** [comment]
The issue with the json stream is reported and should be fixed soon.
