### ISSUE TITLE
Field "extra args" in "modify" dialog not working

### ISSUE THREAD

**Issue by sehucke** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#36]
**Problem:**
- Additional docker params added in the field "extra args" in the "modify" dialog are not used.
- Enter some extra args, click "save" -> Entered values have no effect and are gone when you open the dialog again.

**Expected:**
- Extra args should be correctly applied to the container
- Extra args field should be correctly populated with previously entered data

**My system:**
- OMV 3.0.64 with Linux 4.9.0 backports kernel
- openmediavault-docker-gui 3.1.4
- Docker 1.13.1

**Comment by luxflow** [comment]
it is only ui issue, extraargs works acually
(check with  --priviledged)

I'll be busy now so I cannot help you right now

**Comment by subzero79** [comment]
For this to work every container fired in the ui would have to be registered in the omv backend. This is a big change.

**Comment by sehucke** [comment]
Thanks for the fast response!

You are right @luxflow . Just tested again. Maybe I mixed things up during testing. Sorry for that...

What do you mean @subzero79 with "every container fired in the ui would have to be registered in the omv backend"? Do you mean that you would have to store all input values in a separate database/file for each container? I guess you currently extract the settings of each container from the corresponding config.v2.json? In this case I see your point... definitely a big change.

Nevertheless:
The docker-gui is able to list exposed ports, volumes etc. once the user has entered them. The user expects that it is doing the same for "extra args" as well. IMHO, it would be best to warn the user that this field is a one-timer.

**Comment by Koxx3** [comment]
Hi,
the problem is when you use "modify" from the GUI. The extra arguments are not restored ... if you save, they vanish and the container reset those settings :(
I scratched my head a loooong time with this bug.

**Comment by subzero79** [comment]
I am currently working on this. Analyzing the container metadata I found out a way to retrieve those extra options without having to register containers in Omv db backend. I'll keep updated, I reckon it will take me around two weeks. I've already added the full options for restart policy and basic macvlan support.

**Comment by subzero79** [comment]
I posted a testing version in the forum. All the current running containers will not repopulate the extra arguments on modify or copy.  Just after they are created with the testing version of the plugin

https://forum.openmediavault.org/index.php/Thread/11290-Docker-GUI-plugin-now-stable/?postID=146029#post146029

**Comment by subzero79** [comment]
Closed with c0dd605686a0c10782187252b566255631a3a670
