### ISSUE TITLE
openmediavault-docker-gui 3.1.9 missing for armhf

### ISSUE THREAD

**Issue by zerojay** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#54]
Hi, it appears that there is no 3.1.9 version of docker-gui for the armhf platform. I noticed this when I was attempting to follow someone's guide that appears to require the macvlan driver support for docker-gui only introduced in v3.1.9.

https://dl.bintray.com/openmediavault-plugin-developers/erasmus-docker/pool/main/o/openmediavault-docker-gui/

**Comment by ryecoaaron** [comment]
The plugin working on the armhf platform is a recent change and only available on OMV 4.x.
