### ISSUE TITLE
Since there is no documentation i have no idea what your options actually do.  

### ISSUE THREAD

**Issue by dotbanana** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#58]
So i installed Docker in OMV 3, now i see the settings tab with a couple of options which in my opinion are very vague described. I have no idea what they mean and searching for it doesn't help because it seems you use other descriptions/names as the normal Docker version.  
Let's do it step by step:  

"The location of the Docker base path (this setting is optional and defaults to /var/lib/docker if unset). The plugin must be enabled for a change to be committed"
What is this location? Is it where the Docker files are? But they were installed by the package manager right? If i change it there will Docker move them automatically or is it going to stop work until i move them manually or what does it exactly do?  

"Source path for copying of Docker image/container data"  and "Destination path"
What source path? For what? I have frankly no idea what to put there. What is this script collecting in what directory for what purpose and why is it moving it?  
What does all this do?  

If you answer me i can push maybe a Readme for you guys for this github-project so this doesn't stay some mysterious insider-thingy where you have to go inside the code to see what it does.  

There is nowhere any guide, any tutorial any description to be found. The newest guide in OMV-Forum says that they are expecting a running Docker beforehand but how to do that? 

Thanks in advance

**Comment by subzero79** [comment]
https://forum.openmediavault.org/index.php/Thread/11296-OpenMediaVault-Docker-GUI-Plugin-Usage-x86-64-Arch-only/


The source copy line is gonna get removed in omv4
