### ISSUE TITLE
permit creation of Bridge networks (actually only macvlan are permitted)

### ISSUE THREAD

**Issue by raulfg3** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#74]
Please permit to add new bridge networks by GUI , actually only macvlan are permitted:

https://forum.openmediavault.org/index.php/Thread/11290-Docker-GUI-plugin-now-stable/?postID=182981#post182981

https://docs.docker.com/network/bridge/

https://www.techrepublic.com/article/how-to-create-and-manage-docker-networks/

**Comment by godfuture** [comment]
Normally you want to have DNS resolving in place, as container IPs can change. And features e.g. link were deprecated. All this is now possible with custom bridges. The default bridge is not recommended for production. Custom Bridge support belongs to basic features!

**Comment by ryecoaaron** [comment]
Adding custom bridges is supported by portainer.  The plugin will not have new features added and is not being ported to OMV 5.x.
