### ISSUE TITLE
Autocomplete container side mount binds

### ISSUE THREAD

**Issue by nicjo814** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#8]

**Comment by subzero79** [comment]
As i told in the forum, maybe autocomplete was the wrong word, maybe autofill the right hand side path (containers) and leave to the user fill the left side (host). I know this was problem before because of the plus button and data validation. So i don't know if is possible

**Comment by nicjo814** [comment]
It would probably be possible but requires quite a lot of work since the whole bind-mount/volumes are needs to be redesigned. It would probably be easier after I've made it possible to edit existing "rows".

**Comment by subzero79** [comment]
Well, for now it accomplishes the function, which is easily guide through the container setup. So maybe in another major release
